version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive
    - set PATH="C:\Program Files\LLVM\bin";%PATH%
    - clang-cl -v


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64

build_script:
  - cmake -DCMAKE_CXX_COMPILER=clang-cl .